In [1]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import jensenshannon as jsd

In [2]:
df = pd.read_csv('data.csv')

In [3]:
v = np.array(sorted(list(set(df[['grid_id']].to_numpy().flatten()))))
n = len(v)

print(v)
print(n)

[  4695   5951   7651 ... 350854 350873 350883]
21692


In [4]:
id_accidents = [[len(df[(df['grid_id'] == node) & (df['time slot'] == i)]) for i in range(24)] for node in v]
id_accidents = np.array(id_accidents)
id_accidents # id_accidents[i][j]: number of accidents of 'id v[i]' at 'time slot j' 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [5]:
np.save('id_accidents.npy', id_accidents)

In [6]:
id_accidents = np.load('id_accidents.npy')
id_accidents

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
id_accidents[13]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0])

In [8]:
adj_matrix = np.zeros((n, n))

for i in range(n):
    print(f'i = {i}')
    for j in range(i, n): # adj_matrix is symmetric (adj_matrix[i][j] == adj_matrix[j][i])
        ri = id_accidents[i] / sum(id_accidents[i])
        rj = id_accidents[j] / sum(id_accidents[j])
        # Jensen-Shannon distance is the square root of the Jensen-Shannon divergence
        adj_matrix[i][j] = 1 - jsd(ri, rj) ** 2 

i = 0
i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
i = 9
i = 10
i = 11
i = 12
i = 13
i = 14
i = 15
i = 16
i = 17
i = 18
i = 19
i = 20
i = 21
i = 22
i = 23
i = 24
i = 25
i = 26
i = 27
i = 28
i = 29
i = 30
i = 31
i = 32
i = 33
i = 34
i = 35
i = 36
i = 37
i = 38
i = 39
i = 40
i = 41
i = 42
i = 43
i = 44
i = 45
i = 46
i = 47
i = 48
i = 49
i = 50
i = 51
i = 52
i = 53
i = 54
i = 55
i = 56
i = 57
i = 58
i = 59
i = 60
i = 61
i = 62
i = 63
i = 64
i = 65
i = 66
i = 67
i = 68
i = 69
i = 70
i = 71
i = 72
i = 73
i = 74
i = 75
i = 76
i = 77
i = 78
i = 79
i = 80
i = 81
i = 82
i = 83
i = 84
i = 85
i = 86
i = 87
i = 88
i = 89
i = 90
i = 91
i = 92
i = 93
i = 94
i = 95
i = 96
i = 97
i = 98
i = 99
i = 100
i = 101
i = 102
i = 103
i = 104
i = 105
i = 106
i = 107
i = 108
i = 109
i = 110
i = 111
i = 112
i = 113
i = 114
i = 115
i = 116
i = 117
i = 118
i = 119
i = 120
i = 121
i = 122
i = 123
i = 124
i = 125
i = 126
i = 127
i = 128
i = 129
i = 130
i = 131
i = 132
i = 133
i = 134
i = 135
i = 136
i = 137
i = 13

i = 1034
i = 1035
i = 1036
i = 1037
i = 1038
i = 1039
i = 1040
i = 1041
i = 1042
i = 1043
i = 1044
i = 1045
i = 1046
i = 1047
i = 1048
i = 1049
i = 1050
i = 1051
i = 1052
i = 1053
i = 1054
i = 1055
i = 1056
i = 1057
i = 1058
i = 1059
i = 1060
i = 1061
i = 1062
i = 1063
i = 1064
i = 1065
i = 1066
i = 1067
i = 1068
i = 1069
i = 1070
i = 1071
i = 1072
i = 1073
i = 1074
i = 1075
i = 1076
i = 1077
i = 1078
i = 1079
i = 1080
i = 1081
i = 1082
i = 1083
i = 1084
i = 1085
i = 1086
i = 1087
i = 1088
i = 1089
i = 1090
i = 1091
i = 1092
i = 1093
i = 1094
i = 1095
i = 1096
i = 1097
i = 1098
i = 1099
i = 1100
i = 1101
i = 1102
i = 1103
i = 1104
i = 1105
i = 1106
i = 1107
i = 1108
i = 1109
i = 1110
i = 1111
i = 1112
i = 1113
i = 1114
i = 1115
i = 1116
i = 1117
i = 1118
i = 1119
i = 1120
i = 1121
i = 1122
i = 1123
i = 1124
i = 1125
i = 1126
i = 1127
i = 1128
i = 1129
i = 1130
i = 1131
i = 1132
i = 1133
i = 1134
i = 1135
i = 1136
i = 1137
i = 1138
i = 1139
i = 1140
i = 1141
i = 1142
i = 1143
i = 1144
i

i = 1945
i = 1946
i = 1947
i = 1948
i = 1949
i = 1950
i = 1951
i = 1952
i = 1953
i = 1954
i = 1955
i = 1956
i = 1957
i = 1958
i = 1959
i = 1960
i = 1961
i = 1962
i = 1963
i = 1964
i = 1965
i = 1966
i = 1967
i = 1968
i = 1969
i = 1970
i = 1971
i = 1972
i = 1973
i = 1974
i = 1975
i = 1976
i = 1977
i = 1978
i = 1979
i = 1980
i = 1981
i = 1982
i = 1983
i = 1984
i = 1985
i = 1986
i = 1987
i = 1988
i = 1989
i = 1990
i = 1991
i = 1992
i = 1993
i = 1994
i = 1995
i = 1996
i = 1997
i = 1998
i = 1999
i = 2000
i = 2001
i = 2002
i = 2003
i = 2004
i = 2005
i = 2006
i = 2007
i = 2008
i = 2009
i = 2010
i = 2011
i = 2012
i = 2013
i = 2014
i = 2015
i = 2016
i = 2017
i = 2018
i = 2019
i = 2020
i = 2021
i = 2022
i = 2023
i = 2024
i = 2025
i = 2026
i = 2027
i = 2028
i = 2029
i = 2030
i = 2031
i = 2032
i = 2033
i = 2034
i = 2035
i = 2036
i = 2037
i = 2038
i = 2039
i = 2040
i = 2041
i = 2042
i = 2043
i = 2044
i = 2045
i = 2046
i = 2047
i = 2048
i = 2049
i = 2050
i = 2051
i = 2052
i = 2053
i = 2054
i = 2055
i

i = 2856
i = 2857
i = 2858
i = 2859
i = 2860
i = 2861
i = 2862
i = 2863
i = 2864
i = 2865
i = 2866
i = 2867
i = 2868
i = 2869
i = 2870
i = 2871
i = 2872
i = 2873
i = 2874
i = 2875
i = 2876
i = 2877
i = 2878
i = 2879
i = 2880
i = 2881
i = 2882
i = 2883
i = 2884
i = 2885
i = 2886
i = 2887
i = 2888
i = 2889
i = 2890
i = 2891
i = 2892
i = 2893
i = 2894
i = 2895
i = 2896
i = 2897
i = 2898
i = 2899
i = 2900
i = 2901
i = 2902
i = 2903
i = 2904
i = 2905
i = 2906
i = 2907
i = 2908
i = 2909
i = 2910
i = 2911
i = 2912
i = 2913
i = 2914
i = 2915
i = 2916
i = 2917
i = 2918
i = 2919
i = 2920
i = 2921
i = 2922
i = 2923
i = 2924
i = 2925
i = 2926
i = 2927
i = 2928
i = 2929
i = 2930
i = 2931
i = 2932
i = 2933
i = 2934
i = 2935
i = 2936
i = 2937
i = 2938
i = 2939
i = 2940
i = 2941
i = 2942
i = 2943
i = 2944
i = 2945
i = 2946
i = 2947
i = 2948
i = 2949
i = 2950
i = 2951
i = 2952
i = 2953
i = 2954
i = 2955
i = 2956
i = 2957
i = 2958
i = 2959
i = 2960
i = 2961
i = 2962
i = 2963
i = 2964
i = 2965
i = 2966
i

i = 3767
i = 3768
i = 3769
i = 3770
i = 3771
i = 3772
i = 3773
i = 3774
i = 3775
i = 3776
i = 3777
i = 3778
i = 3779
i = 3780
i = 3781
i = 3782
i = 3783
i = 3784
i = 3785
i = 3786
i = 3787
i = 3788
i = 3789
i = 3790
i = 3791
i = 3792
i = 3793
i = 3794
i = 3795
i = 3796
i = 3797
i = 3798
i = 3799
i = 3800
i = 3801
i = 3802
i = 3803
i = 3804
i = 3805
i = 3806
i = 3807
i = 3808
i = 3809
i = 3810
i = 3811
i = 3812
i = 3813
i = 3814
i = 3815
i = 3816
i = 3817
i = 3818
i = 3819
i = 3820
i = 3821
i = 3822
i = 3823
i = 3824
i = 3825
i = 3826
i = 3827
i = 3828
i = 3829
i = 3830
i = 3831
i = 3832
i = 3833
i = 3834
i = 3835
i = 3836
i = 3837
i = 3838
i = 3839
i = 3840
i = 3841
i = 3842
i = 3843
i = 3844
i = 3845
i = 3846
i = 3847
i = 3848
i = 3849
i = 3850
i = 3851
i = 3852
i = 3853
i = 3854
i = 3855
i = 3856
i = 3857
i = 3858
i = 3859
i = 3860
i = 3861
i = 3862
i = 3863
i = 3864
i = 3865
i = 3866
i = 3867
i = 3868
i = 3869
i = 3870
i = 3871
i = 3872
i = 3873
i = 3874
i = 3875
i = 3876
i = 3877
i

i = 4678
i = 4679
i = 4680
i = 4681
i = 4682
i = 4683
i = 4684
i = 4685
i = 4686
i = 4687
i = 4688
i = 4689
i = 4690
i = 4691
i = 4692
i = 4693
i = 4694
i = 4695
i = 4696
i = 4697
i = 4698
i = 4699
i = 4700
i = 4701
i = 4702
i = 4703
i = 4704
i = 4705
i = 4706
i = 4707
i = 4708
i = 4709
i = 4710
i = 4711
i = 4712
i = 4713
i = 4714
i = 4715
i = 4716
i = 4717
i = 4718
i = 4719
i = 4720
i = 4721
i = 4722
i = 4723
i = 4724
i = 4725
i = 4726
i = 4727
i = 4728
i = 4729
i = 4730
i = 4731
i = 4732
i = 4733
i = 4734
i = 4735
i = 4736
i = 4737
i = 4738
i = 4739
i = 4740
i = 4741
i = 4742
i = 4743
i = 4744
i = 4745
i = 4746
i = 4747
i = 4748
i = 4749
i = 4750
i = 4751
i = 4752
i = 4753
i = 4754
i = 4755
i = 4756
i = 4757
i = 4758
i = 4759
i = 4760
i = 4761
i = 4762
i = 4763
i = 4764
i = 4765
i = 4766
i = 4767
i = 4768
i = 4769
i = 4770
i = 4771
i = 4772
i = 4773
i = 4774
i = 4775
i = 4776
i = 4777
i = 4778
i = 4779
i = 4780
i = 4781
i = 4782
i = 4783
i = 4784
i = 4785
i = 4786
i = 4787
i = 4788
i

i = 5589
i = 5590
i = 5591
i = 5592
i = 5593
i = 5594
i = 5595
i = 5596
i = 5597
i = 5598
i = 5599
i = 5600
i = 5601
i = 5602
i = 5603
i = 5604
i = 5605
i = 5606
i = 5607
i = 5608
i = 5609
i = 5610
i = 5611
i = 5612
i = 5613
i = 5614
i = 5615
i = 5616
i = 5617
i = 5618
i = 5619
i = 5620
i = 5621
i = 5622
i = 5623
i = 5624
i = 5625
i = 5626
i = 5627
i = 5628
i = 5629
i = 5630
i = 5631
i = 5632
i = 5633
i = 5634
i = 5635
i = 5636
i = 5637
i = 5638
i = 5639
i = 5640
i = 5641
i = 5642
i = 5643
i = 5644
i = 5645
i = 5646
i = 5647
i = 5648
i = 5649
i = 5650
i = 5651
i = 5652
i = 5653
i = 5654
i = 5655
i = 5656
i = 5657
i = 5658
i = 5659
i = 5660
i = 5661
i = 5662
i = 5663
i = 5664
i = 5665
i = 5666
i = 5667
i = 5668
i = 5669
i = 5670
i = 5671
i = 5672
i = 5673
i = 5674
i = 5675
i = 5676
i = 5677
i = 5678
i = 5679
i = 5680
i = 5681
i = 5682
i = 5683
i = 5684
i = 5685
i = 5686
i = 5687
i = 5688
i = 5689
i = 5690
i = 5691
i = 5692
i = 5693
i = 5694
i = 5695
i = 5696
i = 5697
i = 5698
i = 5699
i

i = 6500
i = 6501
i = 6502
i = 6503
i = 6504
i = 6505
i = 6506
i = 6507
i = 6508
i = 6509
i = 6510
i = 6511
i = 6512
i = 6513
i = 6514
i = 6515
i = 6516
i = 6517
i = 6518
i = 6519
i = 6520
i = 6521
i = 6522
i = 6523
i = 6524
i = 6525
i = 6526
i = 6527
i = 6528
i = 6529
i = 6530
i = 6531
i = 6532
i = 6533
i = 6534
i = 6535
i = 6536
i = 6537
i = 6538
i = 6539
i = 6540
i = 6541
i = 6542
i = 6543
i = 6544
i = 6545
i = 6546
i = 6547
i = 6548
i = 6549
i = 6550
i = 6551
i = 6552
i = 6553
i = 6554
i = 6555
i = 6556
i = 6557
i = 6558
i = 6559
i = 6560
i = 6561
i = 6562
i = 6563
i = 6564
i = 6565
i = 6566
i = 6567
i = 6568
i = 6569
i = 6570
i = 6571
i = 6572
i = 6573
i = 6574
i = 6575
i = 6576
i = 6577
i = 6578
i = 6579
i = 6580
i = 6581
i = 6582
i = 6583
i = 6584
i = 6585
i = 6586
i = 6587
i = 6588
i = 6589
i = 6590
i = 6591
i = 6592
i = 6593
i = 6594
i = 6595
i = 6596
i = 6597
i = 6598
i = 6599
i = 6600
i = 6601
i = 6602
i = 6603
i = 6604
i = 6605
i = 6606
i = 6607
i = 6608
i = 6609
i = 6610
i

i = 7411
i = 7412
i = 7413
i = 7414
i = 7415
i = 7416
i = 7417
i = 7418
i = 7419
i = 7420
i = 7421
i = 7422
i = 7423
i = 7424
i = 7425
i = 7426
i = 7427
i = 7428
i = 7429
i = 7430
i = 7431
i = 7432
i = 7433
i = 7434
i = 7435
i = 7436
i = 7437
i = 7438
i = 7439
i = 7440
i = 7441
i = 7442
i = 7443
i = 7444
i = 7445
i = 7446
i = 7447
i = 7448
i = 7449
i = 7450
i = 7451
i = 7452
i = 7453
i = 7454
i = 7455
i = 7456
i = 7457
i = 7458
i = 7459
i = 7460
i = 7461
i = 7462
i = 7463
i = 7464
i = 7465
i = 7466
i = 7467
i = 7468
i = 7469
i = 7470
i = 7471
i = 7472
i = 7473
i = 7474
i = 7475
i = 7476
i = 7477
i = 7478
i = 7479
i = 7480
i = 7481
i = 7482
i = 7483
i = 7484
i = 7485
i = 7486
i = 7487
i = 7488
i = 7489
i = 7490
i = 7491
i = 7492
i = 7493
i = 7494
i = 7495
i = 7496
i = 7497
i = 7498
i = 7499
i = 7500
i = 7501
i = 7502
i = 7503
i = 7504
i = 7505
i = 7506
i = 7507
i = 7508
i = 7509
i = 7510
i = 7511
i = 7512
i = 7513
i = 7514
i = 7515
i = 7516
i = 7517
i = 7518
i = 7519
i = 7520
i = 7521
i

i = 8322
i = 8323
i = 8324
i = 8325
i = 8326
i = 8327
i = 8328
i = 8329
i = 8330
i = 8331
i = 8332
i = 8333
i = 8334
i = 8335
i = 8336
i = 8337
i = 8338
i = 8339
i = 8340
i = 8341
i = 8342
i = 8343
i = 8344
i = 8345
i = 8346
i = 8347
i = 8348
i = 8349
i = 8350
i = 8351
i = 8352
i = 8353
i = 8354
i = 8355
i = 8356
i = 8357
i = 8358
i = 8359
i = 8360
i = 8361
i = 8362
i = 8363
i = 8364
i = 8365
i = 8366
i = 8367
i = 8368
i = 8369
i = 8370
i = 8371
i = 8372
i = 8373
i = 8374
i = 8375
i = 8376
i = 8377
i = 8378
i = 8379
i = 8380
i = 8381
i = 8382
i = 8383
i = 8384
i = 8385
i = 8386
i = 8387
i = 8388
i = 8389
i = 8390
i = 8391
i = 8392
i = 8393
i = 8394
i = 8395
i = 8396
i = 8397
i = 8398
i = 8399
i = 8400
i = 8401
i = 8402
i = 8403
i = 8404
i = 8405
i = 8406
i = 8407
i = 8408
i = 8409
i = 8410
i = 8411
i = 8412
i = 8413
i = 8414
i = 8415
i = 8416
i = 8417
i = 8418
i = 8419
i = 8420
i = 8421
i = 8422
i = 8423
i = 8424
i = 8425
i = 8426
i = 8427
i = 8428
i = 8429
i = 8430
i = 8431
i = 8432
i

i = 9233
i = 9234
i = 9235
i = 9236
i = 9237
i = 9238
i = 9239
i = 9240
i = 9241
i = 9242
i = 9243
i = 9244
i = 9245
i = 9246
i = 9247
i = 9248
i = 9249
i = 9250
i = 9251
i = 9252
i = 9253
i = 9254
i = 9255
i = 9256
i = 9257
i = 9258
i = 9259
i = 9260
i = 9261
i = 9262
i = 9263
i = 9264
i = 9265
i = 9266
i = 9267
i = 9268
i = 9269
i = 9270
i = 9271
i = 9272
i = 9273
i = 9274
i = 9275
i = 9276
i = 9277
i = 9278
i = 9279
i = 9280
i = 9281
i = 9282
i = 9283
i = 9284
i = 9285
i = 9286
i = 9287
i = 9288
i = 9289
i = 9290
i = 9291
i = 9292
i = 9293
i = 9294
i = 9295
i = 9296
i = 9297
i = 9298
i = 9299
i = 9300
i = 9301
i = 9302
i = 9303
i = 9304
i = 9305
i = 9306
i = 9307
i = 9308
i = 9309
i = 9310
i = 9311
i = 9312
i = 9313
i = 9314
i = 9315
i = 9316
i = 9317
i = 9318
i = 9319
i = 9320
i = 9321
i = 9322
i = 9323
i = 9324
i = 9325
i = 9326
i = 9327
i = 9328
i = 9329
i = 9330
i = 9331
i = 9332
i = 9333
i = 9334
i = 9335
i = 9336
i = 9337
i = 9338
i = 9339
i = 9340
i = 9341
i = 9342
i = 9343
i

i = 10130
i = 10131
i = 10132
i = 10133
i = 10134
i = 10135
i = 10136
i = 10137
i = 10138
i = 10139
i = 10140
i = 10141
i = 10142
i = 10143
i = 10144
i = 10145
i = 10146
i = 10147
i = 10148
i = 10149
i = 10150
i = 10151
i = 10152
i = 10153
i = 10154
i = 10155
i = 10156
i = 10157
i = 10158
i = 10159
i = 10160
i = 10161
i = 10162
i = 10163
i = 10164
i = 10165
i = 10166
i = 10167
i = 10168
i = 10169
i = 10170
i = 10171
i = 10172
i = 10173
i = 10174
i = 10175
i = 10176
i = 10177
i = 10178
i = 10179
i = 10180
i = 10181
i = 10182
i = 10183
i = 10184
i = 10185
i = 10186
i = 10187
i = 10188
i = 10189
i = 10190
i = 10191
i = 10192
i = 10193
i = 10194
i = 10195
i = 10196
i = 10197
i = 10198
i = 10199
i = 10200
i = 10201
i = 10202
i = 10203
i = 10204
i = 10205
i = 10206
i = 10207
i = 10208
i = 10209
i = 10210
i = 10211
i = 10212
i = 10213
i = 10214
i = 10215
i = 10216
i = 10217
i = 10218
i = 10219
i = 10220
i = 10221
i = 10222
i = 10223
i = 10224
i = 10225
i = 10226
i = 10227
i = 10228
i = 10229


i = 10950
i = 10951
i = 10952
i = 10953
i = 10954
i = 10955
i = 10956
i = 10957
i = 10958
i = 10959
i = 10960
i = 10961
i = 10962
i = 10963
i = 10964
i = 10965
i = 10966
i = 10967
i = 10968
i = 10969
i = 10970
i = 10971
i = 10972
i = 10973
i = 10974
i = 10975
i = 10976
i = 10977
i = 10978
i = 10979
i = 10980
i = 10981
i = 10982
i = 10983
i = 10984
i = 10985
i = 10986
i = 10987
i = 10988
i = 10989
i = 10990
i = 10991
i = 10992
i = 10993
i = 10994
i = 10995
i = 10996
i = 10997
i = 10998
i = 10999
i = 11000
i = 11001
i = 11002
i = 11003
i = 11004
i = 11005
i = 11006
i = 11007
i = 11008
i = 11009
i = 11010
i = 11011
i = 11012
i = 11013
i = 11014
i = 11015
i = 11016
i = 11017
i = 11018
i = 11019
i = 11020
i = 11021
i = 11022
i = 11023
i = 11024
i = 11025
i = 11026
i = 11027
i = 11028
i = 11029
i = 11030
i = 11031
i = 11032
i = 11033
i = 11034
i = 11035
i = 11036
i = 11037
i = 11038
i = 11039
i = 11040
i = 11041
i = 11042
i = 11043
i = 11044
i = 11045
i = 11046
i = 11047
i = 11048
i = 11049


i = 11770
i = 11771
i = 11772
i = 11773
i = 11774
i = 11775
i = 11776
i = 11777
i = 11778
i = 11779
i = 11780
i = 11781
i = 11782
i = 11783
i = 11784
i = 11785
i = 11786
i = 11787
i = 11788
i = 11789
i = 11790
i = 11791
i = 11792
i = 11793
i = 11794
i = 11795
i = 11796
i = 11797
i = 11798
i = 11799
i = 11800
i = 11801
i = 11802
i = 11803
i = 11804
i = 11805
i = 11806
i = 11807
i = 11808
i = 11809
i = 11810
i = 11811
i = 11812
i = 11813
i = 11814
i = 11815
i = 11816
i = 11817
i = 11818
i = 11819
i = 11820
i = 11821
i = 11822
i = 11823
i = 11824
i = 11825
i = 11826
i = 11827
i = 11828
i = 11829
i = 11830
i = 11831
i = 11832
i = 11833
i = 11834
i = 11835
i = 11836
i = 11837
i = 11838
i = 11839
i = 11840
i = 11841
i = 11842
i = 11843
i = 11844
i = 11845
i = 11846
i = 11847
i = 11848
i = 11849
i = 11850
i = 11851
i = 11852
i = 11853
i = 11854
i = 11855
i = 11856
i = 11857
i = 11858
i = 11859
i = 11860
i = 11861
i = 11862
i = 11863
i = 11864
i = 11865
i = 11866
i = 11867
i = 11868
i = 11869


i = 12590
i = 12591
i = 12592
i = 12593
i = 12594
i = 12595
i = 12596
i = 12597
i = 12598
i = 12599
i = 12600
i = 12601
i = 12602
i = 12603
i = 12604
i = 12605
i = 12606
i = 12607
i = 12608
i = 12609
i = 12610
i = 12611
i = 12612
i = 12613
i = 12614
i = 12615
i = 12616
i = 12617
i = 12618
i = 12619
i = 12620
i = 12621
i = 12622
i = 12623
i = 12624
i = 12625
i = 12626
i = 12627
i = 12628
i = 12629
i = 12630
i = 12631
i = 12632
i = 12633
i = 12634
i = 12635
i = 12636
i = 12637
i = 12638
i = 12639
i = 12640
i = 12641
i = 12642
i = 12643
i = 12644
i = 12645
i = 12646
i = 12647
i = 12648
i = 12649
i = 12650
i = 12651
i = 12652
i = 12653
i = 12654
i = 12655
i = 12656
i = 12657
i = 12658
i = 12659
i = 12660
i = 12661
i = 12662
i = 12663
i = 12664
i = 12665
i = 12666
i = 12667
i = 12668
i = 12669
i = 12670
i = 12671
i = 12672
i = 12673
i = 12674
i = 12675
i = 12676
i = 12677
i = 12678
i = 12679
i = 12680
i = 12681
i = 12682
i = 12683
i = 12684
i = 12685
i = 12686
i = 12687
i = 12688
i = 12689


i = 13410
i = 13411
i = 13412
i = 13413
i = 13414
i = 13415
i = 13416
i = 13417
i = 13418
i = 13419
i = 13420
i = 13421
i = 13422
i = 13423
i = 13424
i = 13425
i = 13426
i = 13427
i = 13428
i = 13429
i = 13430
i = 13431
i = 13432
i = 13433
i = 13434
i = 13435
i = 13436
i = 13437
i = 13438
i = 13439
i = 13440
i = 13441
i = 13442
i = 13443
i = 13444
i = 13445
i = 13446
i = 13447
i = 13448
i = 13449
i = 13450
i = 13451
i = 13452
i = 13453
i = 13454
i = 13455
i = 13456
i = 13457
i = 13458
i = 13459
i = 13460
i = 13461
i = 13462
i = 13463
i = 13464
i = 13465
i = 13466
i = 13467
i = 13468
i = 13469
i = 13470
i = 13471
i = 13472
i = 13473
i = 13474
i = 13475
i = 13476
i = 13477
i = 13478
i = 13479
i = 13480
i = 13481
i = 13482
i = 13483
i = 13484
i = 13485
i = 13486
i = 13487
i = 13488
i = 13489
i = 13490
i = 13491
i = 13492
i = 13493
i = 13494
i = 13495
i = 13496
i = 13497
i = 13498
i = 13499
i = 13500
i = 13501
i = 13502
i = 13503
i = 13504
i = 13505
i = 13506
i = 13507
i = 13508
i = 13509


i = 14230
i = 14231
i = 14232
i = 14233
i = 14234
i = 14235
i = 14236
i = 14237
i = 14238
i = 14239
i = 14240
i = 14241
i = 14242
i = 14243
i = 14244
i = 14245
i = 14246
i = 14247
i = 14248
i = 14249
i = 14250
i = 14251
i = 14252
i = 14253
i = 14254
i = 14255
i = 14256
i = 14257
i = 14258
i = 14259
i = 14260
i = 14261
i = 14262
i = 14263
i = 14264
i = 14265
i = 14266
i = 14267
i = 14268
i = 14269
i = 14270
i = 14271
i = 14272
i = 14273
i = 14274
i = 14275
i = 14276
i = 14277
i = 14278
i = 14279
i = 14280
i = 14281
i = 14282
i = 14283
i = 14284
i = 14285
i = 14286
i = 14287
i = 14288
i = 14289
i = 14290
i = 14291
i = 14292
i = 14293
i = 14294
i = 14295
i = 14296
i = 14297
i = 14298
i = 14299
i = 14300
i = 14301
i = 14302
i = 14303
i = 14304
i = 14305
i = 14306
i = 14307
i = 14308
i = 14309
i = 14310
i = 14311
i = 14312
i = 14313
i = 14314
i = 14315
i = 14316
i = 14317
i = 14318
i = 14319
i = 14320
i = 14321
i = 14322
i = 14323
i = 14324
i = 14325
i = 14326
i = 14327
i = 14328
i = 14329


i = 15050
i = 15051
i = 15052
i = 15053
i = 15054
i = 15055
i = 15056
i = 15057
i = 15058
i = 15059
i = 15060
i = 15061
i = 15062
i = 15063
i = 15064
i = 15065
i = 15066
i = 15067
i = 15068
i = 15069
i = 15070
i = 15071
i = 15072
i = 15073
i = 15074
i = 15075
i = 15076
i = 15077
i = 15078
i = 15079
i = 15080
i = 15081
i = 15082
i = 15083
i = 15084
i = 15085
i = 15086
i = 15087
i = 15088
i = 15089
i = 15090
i = 15091
i = 15092
i = 15093
i = 15094
i = 15095
i = 15096
i = 15097
i = 15098
i = 15099
i = 15100
i = 15101
i = 15102
i = 15103
i = 15104
i = 15105
i = 15106
i = 15107
i = 15108
i = 15109
i = 15110
i = 15111
i = 15112
i = 15113
i = 15114
i = 15115
i = 15116
i = 15117
i = 15118
i = 15119
i = 15120
i = 15121
i = 15122
i = 15123
i = 15124
i = 15125
i = 15126
i = 15127
i = 15128
i = 15129
i = 15130
i = 15131
i = 15132
i = 15133
i = 15134
i = 15135
i = 15136
i = 15137
i = 15138
i = 15139
i = 15140
i = 15141
i = 15142
i = 15143
i = 15144
i = 15145
i = 15146
i = 15147
i = 15148
i = 15149


i = 15871
i = 15872
i = 15873
i = 15874
i = 15875
i = 15876
i = 15877
i = 15878
i = 15879
i = 15880
i = 15881
i = 15882
i = 15883
i = 15884
i = 15885
i = 15886
i = 15887
i = 15888
i = 15889
i = 15890
i = 15891
i = 15892
i = 15893
i = 15894
i = 15895
i = 15896
i = 15897
i = 15898
i = 15899
i = 15900
i = 15901
i = 15902
i = 15903
i = 15904
i = 15905
i = 15906
i = 15907
i = 15908
i = 15909
i = 15910
i = 15911
i = 15912
i = 15913
i = 15914
i = 15915
i = 15916
i = 15917
i = 15918
i = 15919
i = 15920
i = 15921
i = 15922
i = 15923
i = 15924
i = 15925
i = 15926
i = 15927
i = 15928
i = 15929
i = 15930
i = 15931
i = 15932
i = 15933
i = 15934
i = 15935
i = 15936
i = 15937
i = 15938
i = 15939
i = 15940
i = 15941
i = 15942
i = 15943
i = 15944
i = 15945
i = 15946
i = 15947
i = 15948
i = 15949
i = 15950
i = 15951
i = 15952
i = 15953
i = 15954
i = 15955
i = 15956
i = 15957
i = 15958
i = 15959
i = 15960
i = 15961
i = 15962
i = 15963
i = 15964
i = 15965
i = 15966
i = 15967
i = 15968
i = 15969
i = 15970


i = 16693
i = 16694
i = 16695
i = 16696
i = 16697
i = 16698
i = 16699
i = 16700
i = 16701
i = 16702
i = 16703
i = 16704
i = 16705
i = 16706
i = 16707
i = 16708
i = 16709
i = 16710
i = 16711
i = 16712
i = 16713
i = 16714
i = 16715
i = 16716
i = 16717
i = 16718
i = 16719
i = 16720
i = 16721
i = 16722
i = 16723
i = 16724
i = 16725
i = 16726
i = 16727
i = 16728
i = 16729
i = 16730
i = 16731
i = 16732
i = 16733
i = 16734
i = 16735
i = 16736
i = 16737
i = 16738
i = 16739
i = 16740
i = 16741
i = 16742
i = 16743
i = 16744
i = 16745
i = 16746
i = 16747
i = 16748
i = 16749
i = 16750
i = 16751
i = 16752
i = 16753
i = 16754
i = 16755
i = 16756
i = 16757
i = 16758
i = 16759
i = 16760
i = 16761
i = 16762
i = 16763
i = 16764
i = 16765
i = 16766
i = 16767
i = 16768
i = 16769
i = 16770
i = 16771
i = 16772
i = 16773
i = 16774
i = 16775
i = 16776
i = 16777
i = 16778
i = 16779
i = 16780
i = 16781
i = 16782
i = 16783
i = 16784
i = 16785
i = 16786
i = 16787
i = 16788
i = 16789
i = 16790
i = 16791
i = 16792


i = 17515
i = 17516
i = 17517
i = 17518
i = 17519
i = 17520
i = 17521
i = 17522
i = 17523
i = 17524
i = 17525
i = 17526
i = 17527
i = 17528
i = 17529
i = 17530
i = 17531
i = 17532
i = 17533
i = 17534
i = 17535
i = 17536
i = 17537
i = 17538
i = 17539
i = 17540
i = 17541
i = 17542
i = 17543
i = 17544
i = 17545
i = 17546
i = 17547
i = 17548
i = 17549
i = 17550
i = 17551
i = 17552
i = 17553
i = 17554
i = 17555
i = 17556
i = 17557
i = 17558
i = 17559
i = 17560
i = 17561
i = 17562
i = 17563
i = 17564
i = 17565
i = 17566
i = 17567
i = 17568
i = 17569
i = 17570
i = 17571
i = 17572
i = 17573
i = 17574
i = 17575
i = 17576
i = 17577
i = 17578
i = 17579
i = 17580
i = 17581
i = 17582
i = 17583
i = 17584
i = 17585
i = 17586
i = 17587
i = 17588
i = 17589
i = 17590
i = 17591
i = 17592
i = 17593
i = 17594
i = 17595
i = 17596
i = 17597
i = 17598
i = 17599
i = 17600
i = 17601
i = 17602
i = 17603
i = 17604
i = 17605
i = 17606
i = 17607
i = 17608
i = 17609
i = 17610
i = 17611
i = 17612
i = 17613
i = 17614


i = 18336
i = 18337
i = 18338
i = 18339
i = 18340
i = 18341
i = 18342
i = 18343
i = 18344
i = 18345
i = 18346
i = 18347
i = 18348
i = 18349
i = 18350
i = 18351
i = 18352
i = 18353
i = 18354
i = 18355
i = 18356
i = 18357
i = 18358
i = 18359
i = 18360
i = 18361
i = 18362
i = 18363
i = 18364
i = 18365
i = 18366
i = 18367
i = 18368
i = 18369
i = 18370
i = 18371
i = 18372
i = 18373
i = 18374
i = 18375
i = 18376
i = 18377
i = 18378
i = 18379
i = 18380
i = 18381
i = 18382
i = 18383
i = 18384
i = 18385
i = 18386
i = 18387
i = 18388
i = 18389
i = 18390
i = 18391
i = 18392
i = 18393
i = 18394
i = 18395
i = 18396
i = 18397
i = 18398
i = 18399
i = 18400
i = 18401
i = 18402
i = 18403
i = 18404
i = 18405
i = 18406
i = 18407
i = 18408
i = 18409
i = 18410
i = 18411
i = 18412
i = 18413
i = 18414
i = 18415
i = 18416
i = 18417
i = 18418
i = 18419
i = 18420
i = 18421
i = 18422
i = 18423
i = 18424
i = 18425
i = 18426
i = 18427
i = 18428
i = 18429
i = 18430
i = 18431
i = 18432
i = 18433
i = 18434
i = 18435


i = 19156
i = 19157
i = 19158
i = 19159
i = 19160
i = 19161
i = 19162
i = 19163
i = 19164
i = 19165
i = 19166
i = 19167
i = 19168
i = 19169
i = 19170
i = 19171
i = 19172
i = 19173
i = 19174
i = 19175
i = 19176
i = 19177
i = 19178
i = 19179
i = 19180
i = 19181
i = 19182
i = 19183
i = 19184
i = 19185
i = 19186
i = 19187
i = 19188
i = 19189
i = 19190
i = 19191
i = 19192
i = 19193
i = 19194
i = 19195
i = 19196
i = 19197
i = 19198
i = 19199
i = 19200
i = 19201
i = 19202
i = 19203
i = 19204
i = 19205
i = 19206
i = 19207
i = 19208
i = 19209
i = 19210
i = 19211
i = 19212
i = 19213
i = 19214
i = 19215
i = 19216
i = 19217
i = 19218
i = 19219
i = 19220
i = 19221
i = 19222
i = 19223
i = 19224
i = 19225
i = 19226
i = 19227
i = 19228
i = 19229
i = 19230
i = 19231
i = 19232
i = 19233
i = 19234
i = 19235
i = 19236
i = 19237
i = 19238
i = 19239
i = 19240
i = 19241
i = 19242
i = 19243
i = 19244
i = 19245
i = 19246
i = 19247
i = 19248
i = 19249
i = 19250
i = 19251
i = 19252
i = 19253
i = 19254
i = 19255


i = 19976
i = 19977
i = 19978
i = 19979
i = 19980
i = 19981
i = 19982
i = 19983
i = 19984
i = 19985
i = 19986
i = 19987
i = 19988
i = 19989
i = 19990
i = 19991
i = 19992
i = 19993
i = 19994
i = 19995
i = 19996
i = 19997
i = 19998
i = 19999
i = 20000
i = 20001
i = 20002
i = 20003
i = 20004
i = 20005
i = 20006
i = 20007
i = 20008
i = 20009
i = 20010
i = 20011
i = 20012
i = 20013
i = 20014
i = 20015
i = 20016
i = 20017
i = 20018
i = 20019
i = 20020
i = 20021
i = 20022
i = 20023
i = 20024
i = 20025
i = 20026
i = 20027
i = 20028
i = 20029
i = 20030
i = 20031
i = 20032
i = 20033
i = 20034
i = 20035
i = 20036
i = 20037
i = 20038
i = 20039
i = 20040
i = 20041
i = 20042
i = 20043
i = 20044
i = 20045
i = 20046
i = 20047
i = 20048
i = 20049
i = 20050
i = 20051
i = 20052
i = 20053
i = 20054
i = 20055
i = 20056
i = 20057
i = 20058
i = 20059
i = 20060
i = 20061
i = 20062
i = 20063
i = 20064
i = 20065
i = 20066
i = 20067
i = 20068
i = 20069
i = 20070
i = 20071
i = 20072
i = 20073
i = 20074
i = 20075


i = 20800
i = 20801
i = 20802
i = 20803
i = 20804
i = 20805
i = 20806
i = 20807
i = 20808
i = 20809
i = 20810
i = 20811
i = 20812
i = 20813
i = 20814
i = 20815
i = 20816
i = 20817
i = 20818
i = 20819
i = 20820
i = 20821
i = 20822
i = 20823
i = 20824
i = 20825
i = 20826
i = 20827
i = 20828
i = 20829
i = 20830
i = 20831
i = 20832
i = 20833
i = 20834
i = 20835
i = 20836
i = 20837
i = 20838
i = 20839
i = 20840
i = 20841
i = 20842
i = 20843
i = 20844
i = 20845
i = 20846
i = 20847
i = 20848
i = 20849
i = 20850
i = 20851
i = 20852
i = 20853
i = 20854
i = 20855
i = 20856
i = 20857
i = 20858
i = 20859
i = 20860
i = 20861
i = 20862
i = 20863
i = 20864
i = 20865
i = 20866
i = 20867
i = 20868
i = 20869
i = 20870
i = 20871
i = 20872
i = 20873
i = 20874
i = 20875
i = 20876
i = 20877
i = 20878
i = 20879
i = 20880
i = 20881
i = 20882
i = 20883
i = 20884
i = 20885
i = 20886
i = 20887
i = 20888
i = 20889
i = 20890
i = 20891
i = 20892
i = 20893
i = 20894
i = 20895
i = 20896
i = 20897
i = 20898
i = 20899


In [9]:
np.save('adj_matrix_risk.npy', adj_matrix)

In [10]:
tmp = adj_matrix.copy()

for i in range(n):
    for j in range(n):
        if i > j: tmp[i][j] = tmp[j][i]
            
tmp

array([[1.        , 0.30685282, 0.30685282, ..., 0.30685282, 0.30685282,
        0.30685282],
       [0.30685282, 1.        , 0.30685282, ..., 0.30685282, 0.30685282,
        0.30685282],
       [0.30685282, 0.30685282, 1.        , ..., 0.68174292, 0.68174292,
        0.68174292],
       ...,
       [0.30685282, 0.30685282, 0.68174292, ..., 1.        , 0.30685282,
        1.        ],
       [0.30685282, 0.30685282, 0.68174292, ..., 0.30685282, 1.        ,
        0.30685282],
       [0.30685282, 0.30685282, 0.68174292, ..., 1.        , 0.30685282,
        1.        ]])

In [11]:
np.save('adj_matrix_risk.npy', tmp)

In [12]:
tmp = np.load('adj_matrix_risk.npy')
tmp

array([[1.        , 0.30685282, 0.30685282, ..., 0.30685282, 0.30685282,
        0.30685282],
       [0.30685282, 1.        , 0.30685282, ..., 0.30685282, 0.30685282,
        0.30685282],
       [0.30685282, 0.30685282, 1.        , ..., 0.68174292, 0.68174292,
        0.68174292],
       ...,
       [0.30685282, 0.30685282, 0.68174292, ..., 1.        , 0.30685282,
        1.        ],
       [0.30685282, 0.30685282, 0.68174292, ..., 0.30685282, 1.        ,
        0.30685282],
       [0.30685282, 0.30685282, 0.68174292, ..., 1.        , 0.30685282,
        1.        ]])